version: "3.9"

services:

  django:
    build: .
    container_name: django_app
    command: python manage.py runserver 0.0.0.0:8000

    volumes:
      - .:/app

    ports:
      - "8000:8000"

    depends_on:
      - db
      - redis

    environment:
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432

      REDIS_HOST: redis
      REDIS_PORT: 6379

  celery:
    build: .
    container_name: celery_worker

    command: celery -A trello worker -l info

    volumes:
      - .:/app

    depends_on:
      - db
      - redis

    environment:
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432

      REDIS_HOST: redis
      REDIS_PORT: 6379

  db:
    image: postgres:17

    container_name: postgres_db

    restart: always

    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7

    container_name: redis_server

    ports:
      - "6379:6379"

volumes:
  postgres_data: