# Generated by Django 6.0.6 on 2026-07-05 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_alter_card_created_at_alter_card_list'),
        ('labels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='cards', to='labels.label'),
        ),
    ]
